name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - fastapi
    - uvicorn
    - python-multipart
    - pymongo
    - pydantic
    - google-generativeai
    - langchain-google-genai
    - sentence-transformers
    - pinecone-client
    - transformers
    - torch
    - python-dotenv
    - langchain
    - google-cloud-aiplatform
    - pymupdf
    - python-jose[cryptography]
    - passlib[bcrypt]